apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: konbini-secure-pass-2026
  POSTGRES_DB: konbini_navi
  DATABASE_URL: postgres://postgres:konbini-secure-pass-2026@postgres:5432/konbini_navi?sslmode=disable
